// Self-host only the exact weights the film uses, so rendering is fully offline
// and fast (no hundreds of live gstatic requests, no proxy-cert problems).
//
// Downloads the `latin` woff2 subset for each family/weight into public/fonts/
// with deterministic names that src/fonts.ts references.

import {execFileSync} from 'node:child_process';
import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(__dirname, '..', 'public', 'fonts');
mkdirSync(FONT_DIR, {recursive: true});

const CA = '/root/.ccr/ca-bundle.crt';
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  {name: 'Bricolage Grotesque', param: 'Bricolage+Grotesque', slug: 'bricolage-grotesque', weights: [700, 800]},
  {name: 'Inter', param: 'Inter', slug: 'inter', weights: [400, 500, 600]},
  {name: 'JetBrains Mono', param: 'JetBrains+Mono', slug: 'jetbrains-mono', weights: [600, 700]},
];

const curl = (url, binary = false) => {
  const args = ['-sS', '--cacert', CA, '-H', `User-Agent: ${UA}`, url];
  return execFileSync('curl', binary ? [...args, '--output', '-'] : args, {
    maxBuffer: 1024 * 1024 * 20,
    encoding: binary ? 'buffer' : 'utf8',
  });
};

const faces = [];
for (const fam of FAMILIES) {
  const wq = fam.weights.join(';');
  const css = curl(
    `https://fonts.googleapis.com/css2?family=${fam.param}:wght@${wq}&display=swap`,
  );
  // split into @font-face blocks, keep only the latin subset (basic-latin range)
  const blocks = css.split('@font-face').slice(1);
  for (const w of fam.weights) {
    const block = blocks.find(
      (b) =>
        new RegExp(`font-weight:\\s*${w};`).test(b) &&
        /unicode-range:[^;]*U\+0000-00FF/.test(b),
    );
    if (!block) {
      throw new Error(`No latin block for ${fam.name} ${w}`);
    }
    const url = block.match(/src:\s*url\((https:[^)]+\.woff2)\)/)[1];
    const data = curl(url, true);
    const file = resolve(FONT_DIR, `${fam.slug}-${w}.woff2`);
    writeFileSync(file, data);
    faces.push({family: fam.name, weight: w, b64: data.toString('base64')});
    console.log(`saved ${fam.slug}-${w}.woff2 (${(data.length / 1024).toFixed(1)} KB)`);
  }
}

// Emit the fonts as base64 data-URI @font-face rules. Inlining avoids any
// runtime fetch (and the flaky CSS-Font-Loading hangs) during headless renders.
const cssRules = faces
  .map(
    (f) =>
      `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};font-display:block;src:url(data:font/woff2;base64,${f.b64}) format('woff2');}`,
  )
  .join('\n');
const specs = faces.map((f) => ({family: f.family, weight: f.weight}));
writeFileSync(
  resolve(__dirname, '..', 'src', 'fonts-face.ts'),
  `// Generated by scripts/fetch-fonts.mjs — do not edit. Base64-inlined woff2.\n` +
    `/* eslint-disable */\n` +
    `export const FONT_FACE_CSS = ${JSON.stringify(cssRules)};\n` +
    `export const FONT_SPECS: {family: string; weight: number}[] = ${JSON.stringify(specs)};\n`,
);
console.log(`Fonts self-hosted in public/fonts/ and inlined into src/fonts-face.ts (${(cssRules.length / 1024).toFixed(0)} KB)`);
